#  ____                   ____                       _     
# | __ )   ___ __      __|  _ \  _   _  _ __    ___ | |__  
# |  _ \  / _ \\ \ /\ / /| |_) || | | || '_ \  / __|| '_ \ 
# | |_) || (_) |\ V  V / |  __/ | |_| || | | || (__ | | | |
# |____/  \___/  \_/\_/  |_|     \__,_||_| |_| \___||_| |_|
#This plugin was made by Fan. All right reserved

BowBoost:
  x: 3
  y: 0.6

#Cooldown in seconds
BowCooldown: 60

BowCooldownMessage: "Please waits §c{time} §fseconds !"